name: Upload Python Package

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.22"
    - name: Build package
      run: uv build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@c12cc61414480c03e10ea76e2a0a1a17d6c764e2
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}